#!/usr/bin/python3
import sys

from helpers import generate_credential_tokens, require_secrets


def main(creds_out):
    require_secrets('osftok', 'triggered-by', 'targets.sec')
    generate_credential_tokens(creds_out)


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit('Usage: %s <creds.zip-out>' % sys.argv[0])
    main(sys.argv[1])
