#!/usr/bin/env bash
# Copyright (c) 2020 Foundries.io
# SPDX-License-Identifier: Apache-2.0
set -euo pipefail

# examples
# sudo is required for apps/containers images dumping
# sudo ./tests/test_apps_publishing.sh $FACTORY $OSF_TOKEN $FIO_USER_ID $FIO_CREDS $FACTORY_DIR/containers.git master

REQ_ARG_NUMB=5
if [[ $# -lt ${REQ_ARG_NUMB} ]]; then
    echo "Insufficient number of parameters"
    exit 1
fi

# Input params
FACTORY=$1
OSF_TOKEN=$2

# jobserv-curl -s https://api.foundries.io/ota/factories/msul-dev01/users/ | jq ".[0].\"polis-id\""
USER_ID=$3

# how to download it for average user??
CREDS_ARCH=$4

# a full path to containers.git repo
APPS_ROOT_DIR=$5

# A tag to apply to newly created Target(s), optional, master by default
OTA_LITE_TAG=${6-"master"}
# Indicates whether to push the new Target(s) to the Factory's TUF repo, optional, off by default
PUSH_TARGET=${7-""}

# a path to the compose publish binary tool, optional, will be donwloaded if not specified
PUBLISH_TOOL=${8-""}
# a dir where the updated creds.zip will be stored along with Factory's TUF repo (keys, targets, etc), optional
WORK_DIR=${9-"$(mktemp -d -t publish-compose-app-XXXXXXXXXX)"}
echo ">> Work dir: ${WORK_DIR}"

ARCHIVE=$WORK_DIR/archive # directory to store artifacts generated by the given script/job
if [[ ! -d ${ARCHIVE} ]]; then
  mkdir "${ARCHIVE}"
fi

SECRETS=$WORK_DIR/secrets # directory to store secrets,
#    - /secrets/osftok - file containing OSF_TOKEN
#    - /secrets/triggered-by - just client_ID from credentials.zip:treehub.json:oauth2:client_id
#    - /secrets/credentials.zip - you Factory OTA creds, created on the first Factory's build
if [[ ! -d ${SECRETS} ]]; then
  mkdir "${SECRETS}"
fi

echo -n "${OSF_TOKEN}" > "${WORK_DIR}/secrets/osftok"
echo -n "${USER_ID}" > "${WORK_DIR}/secrets/triggered-by"

TUF_REPO=$WORK_DIR/tuf-repo # directory for TUF metadata files, must be created by current user

if [[ ! -d ${TUF_REPO} ]]; then
  mkdir "${TUF_REPO}"
fi

DOCKER_COMPOSE_APP_PRELOAD="1"
PRELOAD_DIR="${WORK_DIR}/preload"
if [[ ! -d ${PRELOAD_DIR} ]]; then
  mkdir "${PRELOAD_DIR}"
fi
APP_IMAGE_DIR="${WORK_DIR}/app-images"
if [[ ! -d ${APP_IMAGE_DIR} ]]; then
  mkdir "${APP_IMAGE_DIR}"
fi


CMD=./apps/publish.sh

docker run -v -it --rm --privileged \
  -e FACTORY=$FACTORY \
  -e CREDS_ARCH=/secrets/credentials.zip \
  -e CREDS_ARCH_UPDATED=/secrets/credentials-updated.zip \
  -e TUF_REPO="/tuf-repo/$FACTORY" \
  -e OTA_LITE_TAG=$OTA_LITE_TAG \
  -e APPS_ROOT_DIR=/apps \
  -e PUBLISH_TOOL=/usr/local/bin/compose-publish \
  -e PUSH_TARGETS=$PUSH_TARGET \
  -e DOCKER_COMPOSE_APP_PRELOAD=$DOCKER_COMPOSE_APP_PRELOAD \
  -e PRELOAD_DIR=/preload \
  -e APP_IMAGE_DIR=/app-images \
  -e HOME=/home/test \
  -v $PWD:/ci-scripts \
  -v $ARCHIVE:/archive \
  -v $SECRETS:/secrets \
  -v $TUF_REPO:/tuf-repo \
  -v $APPS_ROOT_DIR:/apps \
  -v $PUBLISH_TOOL:/usr/local/bin/compose-publish \
  -v $CREDS_ARCH:/secrets/credentials.zip \
  -v $PRELOAD_DIR:/preload \
  -v $APP_IMAGE_DIR:/app-images \
  -w /ci-scripts \
  -u $(id -u ${USER}):$(id -g ${USER}) \
  foundries/lmp-image-tools ${CMD}

if [[ $? -eq 0 ]]; then
  echo "Your apps has been successfully published, see the work dir for details: ${WORK_DIR}"
else
  echo "Failed to publish Compose Apps"
fi
