timeout: 30   # the qemu testing can take some time
email:
  users: 'ci-notifications@foundries.io'
triggers:
  - name: fio-pull-request
    type: github_pr
    runs:
      - name: sanity-compile-nrf52
        container: zephyrprojectrtos/zephyr-build
        container-user: root
        container-entrypoint: ""
        host-tag: amd64
        triggers:
          - name: sanity-test
        params:
          SAVE_OUTDIR: "1"
          PLATFORM: nrf52_blenano2
        script-repo:
          name: fio
          path: zephyr/sanity-compile.sh

  - name: upstream-merge
    type: git_poller
    params:
      GIT_URL: https://github.com/zephyrproject-rtos/zephyr.git
      GIT_POLL_REFS: "refs/heads/master"
    runs:
      - name: sanity-compile-nrf52
        container: zephyrprojectrtos/zephyr-build
        container-user: root
        container-entrypoint: ""
        host-tag: amd64
        triggers:
          - name: sanity-test
        params:
          SAVE_OUTDIR: "1"
          PLATFORM: nrf52_blenano2
        script-repo:
          name: fio
          path: zephyr/sanity-compile.sh

      - name: sanity-compile-{loop}
        container: zephyrprojectrtos/zephyr-build
        container-user: root
        container-entrypoint: ""
        host-tag: amd64
        script-repo:
          name: fio
          path: zephyr/sanity-compile.sh
        loop-on:
          - param: PLATFORM
            values: [frdm_k64f, reel_board, nrf52840_pca10056]

      - name: zephyr-sample-mcumgr-{loop}
        container: zephyrprojectrtos/zephyr-build
        container-user: root
        container-entrypoint: ""
        host-tag: amd64
        script-repo:
          name: fio
          path: zephyr/sample.sh
        params:
            APP: samples/subsys/mgmt/mcumgr/smp_svr/
        loop-on:
          - param: PLATFORM
            values: [reel_board, nrf52840_pca10056]

  - name: sanity-test
    type: simple
    runs:
      - name: sanity-test-nrf52
        container: zephyrprojectrtos/zephyr-build
        container-user: root
        container-entrypoint: ""
        host-tag: zephyr-nrf52
        privileged: true
        params:
          PYOCD_BOARD_NAME: RedBearLab-BLE-Nano2
        script-repo:
          name: fio
          path: zephyr/sanity-device.sh


params:
  archive: /archive
  FLAKY_TESTS: |
    tests/benchmarks/sched
    tests/kernel/interrupt
    tests/kernel/sched/schedule_api

script-repos:
  fio:
    clone-url: https://github.com/foundriesio/ci-scripts
