#!/usr/bin/python3

import json
import sys

from docker_registry_client import ThirdPartyRegistry


if len(sys.argv) != 2:
    sys.exit("Usage: %s <registry data file>" % sys.argv[0])

with open(sys.argv[1]) as f:
    registries = json.load(f)

ThirdPartyRegistry(registries).login()
