#!/usr/bin/python3
#
# Copyright (c) 2019 Foundries.io
# SPDX-License-Identifier: Apache-2.0
#
import argparse
import logging
import json
import os

logging.basicConfig(level='INFO')


def merge(args):
    with open(args.targets_json) as f:
        data = json.load(f)

    targets = data['targets']
    changed = False

    cur = targets[args.target_name]
    cur_ver = int(cur['custom']['version'])
    logging.info('Target is: %r', cur)
    tag = os.environ.get('OTA_LITE_TAG')
    if tag:
        logging.info('Settings target tags to: [%s]', tag)
        cur['custom']['tags'] = [tag]
        changed = True

    # Now find the previous version
    prev = None
    prev_ver = 0
    for tgt in targets.values():
        if tgt['custom'].get('name') == cur['custom']['name']:
            match_tag = tag and tag in tgt['custom'].get('tags', [])
            tgt_ver = int(tgt['custom']['version'])
            if match_tag and tgt_ver > prev_ver and tgt_ver < cur_ver:
                prev = tgt
                prev_ver = tgt_ver

    logging.info('Prev is: %r', prev)
    if prev:
        apps = prev['custom'].get('docker_apps')
        if apps:
            logging.info('Updating build to have apps: %r', apps)
            cur['custom']['docker_apps'] = apps
            changed = True

    if changed:
        logging.info('Target has changed, saving changes')
        with open(args.targets_json, 'w') as f:
            json.dump(data, f, indent=2)


def get_args():
    parser = argparse.ArgumentParser(
        '''Do LMP customiziations of the current build target. Including
           copying docker apps defined in the previous build target.''')

    parser.add_argument('targets_json')
    parser.add_argument('target_name')

    return parser.parse_args()


if __name__ == '__main__':
    args = get_args()
    merge(args)
