timeout: 540  # a build with no cache is quite slow
triggers:
  - name: build-release
    type: git_poller
    email:
      users: 'ci-notifications@foundries.io'
    params:
      GIT_URL: |
        https://github.com/foundriesio/lmp-manifest.git
      GIT_POLL_REFS: |
        refs/heads/master
      OTA_LITE_TAG: postmerge
    runs:
      # supported images that have OTA
      - name: supported-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - raspberrypi3-64
        triggers:
          - name: ota-{loop}
          - name: ptest-{loop}
        params:
          IMAGE: lmp-gateway-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # other images that have OTA
      - name: other-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - intel-corei7-64
        triggers:
          - name: ota-{loop}
          - name: ptest-{loop}
        params:
          IMAGE: lmp-gateway-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mini images
      - name: other-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - qemuriscv64
        params:
          IMAGE: lmp-mini-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # Other images with no OTA
      - name: other-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - apalis-imx6
              - apalis-imx8
              - beaglebone-yocto
              - imx8mmevk
              - qemuarm64
              - raspberrypi3
              - raspberrypi4
              - raspberrypi4-64
        params:
          IMAGE: lmp-gateway-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - imx8mmevk
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: build-release-stable
    type: git_poller
    email:
      users: 'ci-notifications@foundries.io'
    params:
      GIT_URL: |
        https://github.com/foundriesio/lmp-manifest.git
      GIT_POLL_REFS: |
        refs/heads/dunfell
      OTA_LITE_TAG: 'postmerge-stable:postmerge'
      AKLITE_TAG: promoted-stable
    runs:
      # supported images
      - name: supported-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - raspberrypi3-64
        params:
          IMAGE: lmp-gateway-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # other images
      - name: other-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - apalis-imx6
              - beaglebone-yocto
              - imx8mmevk
              - intel-corei7-64
              - qemuarm64
              - raspberrypi3
              - raspberrypi4
              - raspberrypi4-64
        params:
          IMAGE: lmp-gateway-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # other mini images
      - name: other-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - qemuriscv64
        params:
          IMAGE: lmp-mini-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - imx8mmevk
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: Code Review
    type: github_pr
    params:
      OTA_LITE_TAG: 'premerge:postmerge'
      AKLITE_TAG: premerge
    runs:
      - name: build-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - raspberrypi3-64
              - intel-corei7-64
        triggers:
          - name: ota-{loop}
          - name: ptest-{loop}
        params:
          IMAGE: lmp-gateway-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      - name: build-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - beaglebone-yocto
        params:
          IMAGE: lmp-gateway-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      - name: build-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - qemuriscv64
        params:
          IMAGE: lmp-mini-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      - name: build-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - apalis-imx6
              - apalis-imx8
              - imx8mmevk
              - qemuarm64
              - raspberrypi3
              - raspberrypi4
              - raspberrypi4-64
        params:
          IMAGE: lmp-gateway-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: build-mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - imx8mmevk
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: ptest-raspberrypi3-64
    type: simple
    runs:
      - name: lmp-ptest-raspberrypi3-64
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        params:
          IMAGE: lmp-gateway-image
          MACHINE: raspberrypi3-64
          ENABLE_PTEST: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: ptest-intel-corei7-64
    type: simple
    runs:
      - name: lmp-ptest-intel-corei7-64
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        params:
          IMAGE: lmp-gateway-image
          MACHINE: intel-corei7-64
          ENABLE_PTEST: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: ota-raspberrypi3-64
    type: simple
    runs:
      - name: lmp-ota-raspberrypi3-64
        container: hub.foundries.io/ota-runner
        host-tag: raspberrypi3-64-ota
        privileged: true
        test-grepping:
          test-pattern: "^Starting Test Suite: (?P<name>\\S+)"
          result-pattern: "^Test Result: (?P<name>\\S+) = (?P<result>(PASSED|FAILED))$"
        script-repo:
          name: fio
          path: lmp/ota.sh

  - name: ota-intel-corei7-64
    type: simple
    runs:
      - name: lmp-ota-intel-corei7-64
        container: hub.foundries.io/ota-runner
        host-tag: amd64-ota
        privileged: true
        test-grepping:
          test-pattern: "^Starting Test Suite: (?P<name>\\S+)"
          result-pattern: "^Test Result: (?P<name>\\S+) = (?P<result>(PASSED|FAILED))$"
        script-repo:
          name: fio
          path: lmp/ota.sh

params:
  archive: /archive
  DISTRO: lmp
  SOTA_PACKED_CREDENTIALS: /var/cache/bitbake/credentials.zip
  SOTA_CLIENT: aktualizr-lite
  EXTRA_IMAGE_INSTALL: aktualizr-lite-public-stream
  OSTREE_BRANCHNAME: lmp

script-repos:
  fio:
    clone-url: https://github.com/foundriesio/ci-scripts
