timeout: 540  # a build with no cache is quite slow
triggers:
  - name: build-eol
    type: git_poller
    email:
      users: 'ci-notifications@foundries.io'
    webhooks:
      - url: https://conductor.infra.foundries.io/api/lmp/
        only_failures: false
        secret_name: lava-webhook-key
    params:
      GIT_URL: |
        https://github.com/foundriesio/lmp-manifest.git
      GIT_POLL_REFS: |
        refs/heads/kirkstone
      OTA_LITE_TAG: kirkstone
      AKLITE_TAG: promoted-kirkstone

    runs:
      # images with no OTA
      - name: "{loop}"
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - am62xx-evm
              - am64xx-evm
              - beaglebone-yocto
              - generic-arm64
              - intel-corei7-64
              - imx6ullevk
              - imx6ullevk-sec
              - imx8mm-lpddr4-evk
              - imx8mm-lpddr4-evk-sec
              - imx8mp-lpddr4-evk
              - imx8mp-lpddr4-evk-sec
              - imx8mn-ddr4-evk
              - imx8mn-ddr4-evk-sec
              - imx8mn-lpddr4-evk
              - imx8mn-lpddr4-evk-sec
              - imx8mq-evk
              - imx93-11x11-lpddr4x-evk
              - jetson-orin-nano-devkit-nvme
              - jetson-agx-xavier-devkit
              - jetson-agx-orin-devkit
              - qemuarm64-secureboot
              - raspberrypi4-64
              - raspberrypi5
              - stm32mp15-disco
              - stm32mp15-disco-sec
              - stm32mp15-eval
              - stm32mp15-eval-sec
              - kv260
              - vck190-versal
        params:
          IMAGE: lmp-base-console-image
          MFGTOOL_FLASH_IMAGE: lmp-base-console-image
          EULA_stm32mp15eval: "1"
          EULA_stm32mp15disco: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - imx6ullevk
              - imx6ullevk-sec
              - imx8mm-lpddr4-evk
              - imx8mm-lpddr4-evk-sec
              - imx8mp-lpddr4-evk
              - imx8mp-lpddr4-evk-sec
              - imx8mn-ddr4-evk
              - imx8mn-ddr4-evk-sec
              - imx8mn-lpddr4-evk
              - imx8mn-lpddr4-evk-sec
              - imx8mq-evk
              - imx93-11x11-lpddr4x-evk
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # STM32 mfgtool
      - name: mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - stm32mp15-disco-sec
              - stm32mp15-eval-sec
        params:
          DISTRO: lmp-mfgtool
          IMAGE: stm32-mfgtool-files
          EXTRA_ARTIFACTS: "stm32-mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # TI mfgtool
      - name: mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - am62xx-evm
        params:
          DISTRO: lmp-mfgtool
          IMAGE: ti-mfgtool-files
          EXTRA_ARTIFACTS: "ti-mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: build-lts
    type: git_poller
    email:
      users: 'ci-notifications@foundries.io'
    webhooks:
      - url: https://conductor.infra.foundries.io/api/lmp/
        only_failures: false
        secret_name: lava-webhook-key
    params:
      GIT_URL: |
        https://github.com/foundriesio/lmp-manifest.git
      GIT_POLL_REFS: |
        refs/heads/scarthgap
      OTA_LITE_TAG: 'scarthgap'
      AKLITE_TAG: promoted-scarthgap
    runs:
      - name: lmp-sdk
        host-tag: amd64
        container: foundries/dind-ci:19.03.9_b38f166
        privileged: true
        script-repo:
          name: fio
          path: lmp/build-sdk-container.sh
      # images with no OTA
      - name: "{loop}"
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - am62xx-evm
              - am64xx-evm
              - beaglebone-yocto
              - generic-arm64
              - intel-corei7-64
              - imx6ullevk
              - imx6ullevk-sec
              - imx8mm-lpddr4-evk
              - imx8mm-lpddr4-evk-sec
              - imx8mp-lpddr4-evk
              - imx8mp-lpddr4-evk-sec
              - imx8mn-ddr4-evk
              - imx8mn-ddr4-evk-sec
              - imx8mn-lpddr4-evk
              - imx8mn-lpddr4-evk-sec
              - imx8mq-evk
              - imx93-11x11-lpddr4x-evk
              - jetson-orin-nano-devkit-nvme
              - jetson-agx-xavier-devkit
              - jetson-agx-orin-devkit
              - qemuarm64-secureboot
              - raspberrypi4-64
              - raspberrypi5
        params:
          IMAGE: lmp-base-console-image
          MFGTOOL_FLASH_IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - imx6ullevk
              - imx6ullevk-sec
              - imx8mm-lpddr4-evk
              - imx8mp-lpddr4-evk
              - imx8mn-ddr4-evk
              - imx8mn-lpddr4-evk
              - imx8mq-evk
              - imx93-11x11-lpddr4x-evk
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # wayland distro flavor
      - name: build-lmp-wayland-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - imx8mm-lpddr4-evk
              - intel-corei7-64
        params:
          DISTRO: lmp-wayland
          IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: build-main
    type: git_poller
    email:
      users: 'ci-notifications@foundries.io'
    webhooks:
      - url: https://conductor.infra.foundries.io/api/lmp/
        only_failures: false
        secret_name: lava-webhook-key
    params:
      GIT_URL: |
        https://github.com/foundriesio/lmp-manifest.git
      GIT_POLL_REFS: |
        refs/heads/main
      OTA_LITE_TAG: 'main'
      AKLITE_TAG: promoted-main
    runs:
      - name: lmp-sdk-next
        host-tag: amd64
        container: foundries/dind-ci:19.03.9_b38f166
        privileged: true
        params:
           LATEST: next
        script-repo:
          name: fio
          path: lmp/build-sdk-container.sh
      # images with no OTA
      - name: "{loop}"
        container: hub.foundries.io/lmp-sdk:next
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - intel-corei7-64
              - qemuarm64-secureboot
        params:
          IMAGE: lmp-base-console-image
          MFGTOOL_FLASH_IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # wayland distro flavor
      - name: build-lmp-wayland-{loop}
        container: hub.foundries.io/lmp-sdk:next
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - intel-corei7-64
        params:
          DISTRO: lmp-wayland
          IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: Code Review
    type: github_pr
    webhooks:
      - url: https://conductor.infra.foundries.io/api/lmp/
        only_failures: false
        secret_name: lava-webhook-key
    params:
      OTA_LITE_TAG: 'premerge:main'
      AKLITE_TAG: premerge
    runs:
      - name: build-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - am62xx-evm
              - am64xx-evm
              - beaglebone-yocto
              - generic-arm64
              - intel-corei7-64
              - imx6ullevk
              - imx6ullevk-sec
              - imx8mm-lpddr4-evk
              - imx8mm-lpddr4-evk-sec
              - imx8mp-lpddr4-evk
              - imx8mp-lpddr4-evk-sec
              - imx8mn-ddr4-evk
              - imx8mn-ddr4-evk-sec
              - imx8mn-lpddr4-evk
              - imx8mn-lpddr4-evk-sec
              - imx8mq-evk
              - imx93-11x11-lpddr4x-evk
              - jetson-orin-nano-devkit-nvme
              - jetson-agx-xavier-devkit
              - jetson-agx-orin-devkit
              - qemuarm64-secureboot
              - raspberrypi4-64
        params:
          BITBAKE_EXTRA_ARGS: --continue
          IMAGE: lmp-base-console-image
          MFGTOOL_FLASH_IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      - name: build-lmp-wayland-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - imx8mm-lpddr4-evk
              - intel-corei7-64
        params:
          BITBAKE_EXTRA_ARGS: --continue
          DISTRO: lmp-wayland
          IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      - name: build-lmp-xwayland-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - imx8mm-lpddr4-evk
              - intel-corei7-64
        params:
          BITBAKE_EXTRA_ARGS: --continue
          DISTRO: lmp-xwayland
          IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: build-mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - imx6ullevk
              - imx6ullevk-sec
              - imx8mm-lpddr4-evk
              - imx8mm-lpddr4-evk-sec
              - imx8mp-lpddr4-evk
              - imx8mp-lpddr4-evk-sec
              - imx8mn-ddr4-evk
              - imx8mn-ddr4-evk-sec
              - imx8mn-lpddr4-evk
              - imx8mn-lpddr4-evk-sec
              - imx8mq-evk
              - imx93-11x11-lpddr4x-evk
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # TI mfgtool
      - name: build-mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-partner-gcp-nocache
        loop-on:
          - param: MACHINE
            values:
              - am62xx-evm
        params:
          DISTRO: lmp-mfgtool
          IMAGE: ti-mfgtool-files
          EXTRA_ARTIFACTS: "ti-mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

params:
  archive: /archive
  DISTRO: lmp
  SOTA_CLIENT: aktualizr-lite
  SOTA_TUF_ROOT_PROVISION: "0"
  OSTREE_BRANCHNAME: lmp

script-repos:
  fio:
    clone-url: https://github.com/foundriesio/ci-scripts
