timeout: 540  # a build with no cache is quite slow
triggers:
  - name: build-release
    type: git_poller
    email:
      users: 'ci-notifications@foundries.io'
    webhooks:
      - url: https://conductor.infra.foundries.io/api/lmp/
        only_failures: false
        secret_name: lava-webhook-key
    params:
      GIT_URL: |
        https://github.com/foundriesio/lmp-manifest.git
      GIT_POLL_REFS: |
        refs/heads/main
      OTA_LITE_TAG: postmerge
    runs:
      # images that have ptest
      - name: "{loop}"
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - intel-corei7-64
        triggers:
          - name: ptest-build-{loop}
        params:
          IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # images with no OTA
      - name: "{loop}"
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - am62xx-evm
              - am64xx-evm
              - apalis-imx6
              - apalis-imx6-sec
              - apalis-imx8
              - beaglebone-yocto
              - generic-arm64
              - imx6ulevk
              - imx6ullevk
              - imx6ullevk-sec
              - imx7ulpea-ucom
              - imx8mm-lpddr4-evk
              - imx8mm-lpddr4-evk-sec
              - imx8mp-lpddr4-evk
              - imx8mp-lpddr4-evk-sec
              - imx8mq-evk
              - imx8qm-mek
              - jetson-agx-xavier-devkit
              - qemuarm
              - qemuarm64-secureboot
              - qemuriscv64
              - raspberrypi4-64
              - stm32mp15-disco
              - stm32mp15-eval
              - kv260
              - kv260-ebbr
              - vck190-versal
              - uz3eg-iocc
              - uz3eg-iocc-sec
              - uz3eg-iocc-ebbr
              - uz3eg-iocc-ebbr-sec
        params:
          IMAGE: lmp-base-console-image
          MFGTOOL_FLASH_IMAGE: lmp-base-console-image
          EULA_stm32mp15eval: "1"
          EULA_stm32mp15disco: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - apalis-imx6
              - apalis-imx6-sec
              - apalis-imx8
              - imx6ulevk
              - imx6ullevk
              - imx6ullevk-sec
              - imx7ulpea-ucom
              - imx8mm-lpddr4-evk
              - imx8mm-lpddr4-evk-sec
              - imx8mp-lpddr4-evk
              - imx8mp-lpddr4-evk-sec
              - imx8mq-evk
              - imx8qm-mek
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: build-main-next
    type: git_poller
    email:
      users: 'ci-notifications@foundries.io'
    webhooks:
      - url: https://conductor.infra.foundries.io/api/lmp/
        only_failures: false
        secret_name: lava-webhook-key
    params:
      GIT_URL: |
        https://github.com/foundriesio/lmp-manifest.git
      GIT_POLL_REFS: |
        refs/heads/main-next
      OTA_LITE_TAG: 'postmerge-next:postmerge'
      AKLITE_TAG: promoted-next
    runs:
      # images that have ptest
      - name: "{loop}"
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - intel-corei7-64
        triggers:
          - name: ptest-build-{loop}
        params:
          IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # images with no OTA
      - name: "{loop}"
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - beaglebone-yocto
              - generic-arm64
              - qemuarm
              - qemuarm64-secureboot
              - qemuriscv64
              - raspberrypi4-64
        params:
          IMAGE: lmp-base-console-image
          MFGTOOL_FLASH_IMAGE: lmp-base-console-image
          EULA_stm32mp1eval: "1"
          EULA_stm32mp1disco: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: build-release-stable
    type: git_poller
    email:
      users: 'ci-notifications@foundries.io'
    params:
      GIT_URL: |
        https://github.com/foundriesio/lmp-manifest.git
      GIT_POLL_REFS: |
        refs/heads/honister
      OTA_LITE_TAG: 'postmerge-stable:postmerge'
      AKLITE_TAG: promoted-stable
    runs:
      - name: "{loop}"
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - am62xx-evm
              - am64xx-evm
              - apalis-imx6
              - apalis-imx6-sec
              - apalis-imx8
              - beaglebone-yocto
              - corstone700-mps3
              - generic-arm64
              - imx6ulevk
              - imx6ullevk
              - imx6ullevk-sec
              - imx7ulpea-ucom
              - imx8mm-lpddr4-evk
              - imx8mm-lpddr4-evk-sec
              - imx8mp-lpddr4-evk
              - imx8mp-lpddr4-evk-sec
              - imx8mq-evk
              - imx8qm-mek
              - jetson-agx-xavier-devkit
              - qemuarm
              - qemuarm64-secureboot
              - qemuriscv64
              - raspberrypi4-64
              - stm32mp1-disco
              - kv260
              - kv260-ebbr
              - vck190-versal
              - uz3eg-iocc
              - uz3eg-iocc-sec
              - uz3eg-iocc-ebbr
              - uz3eg-iocc-ebbr-sec
        params:
          IMAGE: lmp-base-console-image
          MFGTOOL_FLASH_IMAGE: lmp-base-console-image
          EULA_stm32mp1eval: "1"
          EULA_stm32mp1disco: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - apalis-imx6
              - apalis-imx6-sec
              - apalis-imx8
              - imx6ulevk
              - imx6ullevk
              - imx6ullevk-sec
              - imx7ulpea-ucom
              - imx8mm-lpddr4-evk
              - imx8mm-lpddr4-evk-sec
              - imx8mp-lpddr4-evk
              - imx8mp-lpddr4-evk-sec
              - imx8mq-evk
              - imx8qm-mek
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: Code Review
    type: github_pr
    params:
      OTA_LITE_TAG: 'premerge:postmerge'
      AKLITE_TAG: premerge
    runs:
      - name: build-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - intel-corei7-64
        triggers:
          - name: ptest-build-{loop}
        params:
          IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      - name: build-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - am62xx-evm
              - am64xx-evm
              - apalis-imx6
              - apalis-imx6-sec
              - apalis-imx8
              - beaglebone-yocto
              - generic-arm64
              - imx6ulevk
              - imx6ullevk
              - imx6ullevk-sec
              - imx7ulpea-ucom
              - imx8mm-lpddr4-evk
              - imx8mm-lpddr4-evk-sec
              - imx8mp-lpddr4-evk
              - imx8mp-lpddr4-evk-sec
              - imx8mq-evk
              - imx8qm-mek
              - jetson-agx-xavier-devkit
              - qemuarm
              - qemuarm64-secureboot
              - qemuriscv64
              - raspberrypi4-64
              - stm32mp15-disco
              - stm32mp15-eval
              - kv260
              - kv260-ebbr
              - vck190-versal
              - uz3eg-iocc
              - uz3eg-iocc-sec
              - uz3eg-iocc-ebbr
              - uz3eg-iocc-ebbr-sec
        params:
          IMAGE: lmp-base-console-image
          MFGTOOL_FLASH_IMAGE: lmp-base-console-image
          EULA_stm32mp15eval: "1"
          EULA_stm32mp15disco: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      - name: build-lmp-base-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - raspberrypi4-64
              - apalis-imx6
              - apalis-imx8
              - imx8mm-lpddr4-evk
              - stm32mp15-disco
        params:
          DISTRO: lmp-base
          IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: build-mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - apalis-imx6
              - apalis-imx6-sec
              - apalis-imx8
              - imx6ulevk
              - imx6ullevk
              - imx6ullevk-sec
              - imx7ulpea-ucom
              - imx8mm-lpddr4-evk
              - imx8mm-lpddr4-evk-sec
              - imx8mp-lpddr4-evk
              - imx8mp-lpddr4-evk-sec
              - imx8mq-evk
              - imx8qm-mek
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: ptest-build-intel-corei7-64
    type: simple
    runs:
      - name: build-intel-corei7-64-ptest
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        params:
          IMAGE: lmp-base-console-image
          MACHINE: intel-corei7-64
          ENABLE_PTEST: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

params:
  archive: /archive
  DISTRO: lmp
  SOTA_PACKED_CREDENTIALS: /var/cache/bitbake/credentials.zip
  SOTA_CLIENT: aktualizr-lite
  EXTRA_IMAGE_INSTALL: aktualizr-lite-public-stream
  OSTREE_BRANCHNAME: lmp

script-repos:
  fio:
    clone-url: https://github.com/foundriesio/ci-scripts
