timeout: 540  # a build with no cache is quite slow
triggers:
  - name: build-release
    type: git_poller
    email:
      users: 'ci-notifications@foundries.io'
    webhooks:
      - url: https://conductor.infra.foundries.io/api/lmp/
        only_failures: false
        secret_name: lava
    params:
      GIT_URL: |
        https://github.com/foundriesio/lmp-manifest.git
      GIT_POLL_REFS: |
        refs/heads/master
      OTA_LITE_TAG: postmerge
    runs:
      # images that have OTA and ptest
      - name: "{loop}"
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - intel-corei7-64
        triggers:
          - name: ota-{loop}
          - name: ptest-build-{loop}
        params:
          IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # images with no OTA
      - name: "{loop}"
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - am64xx-sk
              - apalis-imx6
              - apalis-imx8
              - beaglebone-yocto
              - corstone700-mps3
              - freedom-u540
              - imx6ullevk
              - imx7ulpea-ucom
              - imx8mmevk
              - imx8mqevk
              - n1sdp
              - qemuarm
              - qemuarm64
              - qemuriscv64
              - raspberrypi3
              - raspberrypi3-64
              - raspberrypi4
              - raspberrypi4-64
              - stm32mp1-disco
              - uz3eg-iocc
        params:
          IMAGE: lmp-base-console-image
          MFGTOOL_FLASH_IMAGE: lmp-base-console-image
          EULA_stm32mp1eval: "1"
          EULA_stm32mp1disco: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - apalis-imx6
              - apalis-imx8
              - imx6ullevk
              - imx7ulpea-ucom
              - imx8mmevk
              - imx8mqevk
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: build-release-stable
    type: git_poller
    email:
      users: 'ci-notifications@foundries.io'
    params:
      GIT_URL: |
        https://github.com/foundriesio/lmp-manifest.git
      GIT_POLL_REFS: |
        refs/heads/gatesgarth
      OTA_LITE_TAG: 'postmerge-stable:postmerge'
      AKLITE_TAG: promoted-stable
    runs:
      - name: "{loop}"
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - am64xx-sk
              - apalis-imx6
              - apalis-imx8
              - beaglebone-yocto
              - corstone700-mps3
              - freedom-u540
              - imx6ullevk
              - imx7ulpea-ucom
              - imx8mmevk
              - imx8mqevk
              - intel-corei7-64
              - n1sdp
              - qemuarm
              - qemuarm64
              - qemuriscv64
              - raspberrypi3
              - raspberrypi3-64
              - raspberrypi4
              - raspberrypi4-64
              - stm32mp1-disco
              - uz3eg-iocc
        params:
          IMAGE: lmp-base-console-image
          MFGTOOL_FLASH_IMAGE: lmp-base-console-image
          EULA_stm32mp1eval: "1"
          EULA_stm32mp1disco: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - apalis-imx6
              - apalis-imx8
              - imx6ullevk
              - imx7ulpea-ucom
              - imx8mmevk
              - imx8mqevk
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: Code Review
    type: github_pr
    params:
      OTA_LITE_TAG: 'premerge:postmerge'
      AKLITE_TAG: premerge
    runs:
      - name: build-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - intel-corei7-64
        triggers:
          - name: ota-{loop}
          - name: ptest-build-{loop}
        params:
          IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      - name: build-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - am64xx-sk
              - apalis-imx6
              - apalis-imx8
              - beaglebone-yocto
              - corstone700-mps3
              - freedom-u540
              - imx6ullevk
              - imx7ulpea-ucom
              - imx8mmevk
              - imx8mqevk
              - n1sdp
              - qemuarm
              - qemuarm64
              - qemuriscv64
              - raspberrypi3
              - raspberrypi3-64
              - raspberrypi4
              - raspberrypi4-64
              - stm32mp1-disco
              - uz3eg-iocc
        params:
          IMAGE: lmp-base-console-image
          MFGTOOL_FLASH_IMAGE: lmp-base-console-image
          EULA_stm32mp1eval: "1"
          EULA_stm32mp1disco: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      - name: build-lmp-base-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - raspberrypi3-64
              - raspberrypi4-64
              - apalis-imx6
              - apalis-imx8
              - imx8mmevk
        params:
          DISTRO: lmp-base
          IMAGE: lmp-base-console-image
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

      # mfgtool / uuu related build files
      - name: build-mfgtool-{loop}
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        loop-on:
          - param: MACHINE
            values:
              - apalis-imx6
              - apalis-imx8
              - imx6ullevk
              - imx7ulpea-ucom
              - imx8mmevk
              - imx8mqevk
        params:
          DISTRO: lmp-mfgtool
          IMAGE: mfgtool-files
          EXTRA_ARTIFACTS: "mfgtool-files.tar.gz"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: ptest-build-intel-corei7-64
    type: simple
    runs:
      - name: build-intel-corei7-64-ptest
        container: hub.foundries.io/lmp-sdk
        host-tag: amd64-osf
        params:
          IMAGE: lmp-base-console-image
          MACHINE: intel-corei7-64
          ENABLE_PTEST: "1"
        script-repo:
          name: fio
          path: lmp/build.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: ota-intel-corei7-64
    type: simple
    runs:
      - name: lmp-ota-intel-corei7-64
        container: hub.foundries.io/ota-runner
        host-tag: amd64-ota
        privileged: true
        test-grepping:
          test-pattern: "^Starting Test Suite: (?P<name>\\S+)"
          result-pattern: "^Test Result: (?P<name>\\S+) = (?P<result>(PASSED|FAILED))$"
        script-repo:
          name: fio
          path: lmp/ota.sh

params:
  archive: /archive
  DISTRO: lmp
  SOTA_PACKED_CREDENTIALS: /var/cache/bitbake/credentials.zip
  SOTA_CLIENT: aktualizr-lite
  EXTRA_IMAGE_INSTALL: aktualizr-lite-public-stream
  OSTREE_BRANCHNAME: lmp

script-repos:
  fio:
    clone-url: https://github.com/foundriesio/ci-scripts
