name: unit-tests
on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image:
        foundries/lmp-image-tools:latest
      volumes:
        - /tmp:/archive

    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory "%(prefix)/$GITHUB_WORKSPACE"
      - run: ./unit-test.sh
